### ISSUE TITLE
Signature check fails

### ISSUE THREAD

**Issue by SGS-1989** [center-for-learning-management/moodle-local_webuntis#4]
Guten Tag,
dieses Plugin ist echt toll, aber ich hatte Probleme mit dem Übertragen der Credentials aus WebUntis. Mit den zwei Public Keys, die als default hinterlegt sind, scheitert die Verifikation auf unserem Moodle-System. Daher musste ich den Signature Check durch einen Bypass ($verified=true;) überspringen, was das Problem für den ersten Import gelöst hat. (So war es auch vor dem letzten Commit an der credentials.php) 
Entweder sind die hinterlegten Public Keys falsch oder es gibt einen Fehler beim Signature Check, den ich aber auch nicht finden konnte.

Beste Grüße
Simon Scheeren

**Comment by rschrenk** [comment]
Hallo,

die Keys können je nach WebUntis-Umgebung abweichen. Am besten nehmen Sie Kontakt mit dem WebUntis-Support auf und fragen dort nach.

LG
