### ISSUE TITLE
webunits does not obey $CFG->proxy* settings

### ISSUE THREAD

**Issue by GGeorggg** [center-for-learning-management/moodle-local_webuntis#5]
The function should use the Moodle FileAPI to setup a Http Request or should import the $CFG->proxy* before calling curl

https://github.com/center-for-learning-management/moodle-local_webuntis/blob/5eb058c231db75a406994659c8ca0a67a84a9807/classes/locallib.php#L188-L239

**Comment by gtndevel** [comment]
fixed
