### ISSUE TITLE
Not sufficient profile data, missing username

### ISSUE THREAD

**Issue by leilich** [center-for-learning-management/moodle-local_webuntis#7]
What ist "sufficient profile data in WebUntis?"
I filled in every field I could find for Admin|Users (Administration|Benutzer) and Students (Stammdaten|Schülerinnen), but get the reply "Ein Nutzerkonto kann aufgrund fehlender Profildaten von WebUntis nicht erstellt werden."
Seems that username is soehow not transferred from WebUntis to the moodle plugin. Can't figure out where ist gets lost.
![nutzerkonto](https://github.com/center-for-learning-management/moodle-local_webuntis/assets/25406951/75b787b7-ccf5-45d2-bac4-006ec3c660de)
![nutzerkonto 2](https://github.com/center-for-learning-management/moodle-local_webuntis/assets/25406951/75e7d282-e621-4f77-adf6-06e5cdaa3741)
![nutzerkonto 3](https://github.com/center-for-learning-management/moodle-local_webuntis/assets/25406951/c7cde5e4-3325-4c84-9c8f-a9cf8fec403e)

**Comment by leilich** [comment]
Activating curldebugging didn't reveal any useful information for me. :-(

**Comment by LaAdolph** [comment]
Got this problem too. Is this a problem which is worked on?
I mean is a year since it showed up.

**Comment by leilich** [comment]
Sorry, forgot that I opened that issue here. Sory again the problem doesn't exist anymore but I don't know exactly why not. :-(
I remember it was a problem in the initial communication with the Moodle-Plugin and the Platform-Module in WebUntis; it had to do with the order of steps to do in Moodle an WebUntis.
