### ISSUE TITLE
webUntis: Schulname zu TenantID

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_webuntis#8]
Dear integration partners,
we introduce a new version of the authorization endpoints!  
The new version (v2) uses the tenantId instead of the flaky schoolname. 
We want to get rid of the schoolname in context of our platform-applications. So after this change, it's no longer necessary for you to know the schoolname. Every communication with the WebUntis Platform should be done via tenantId.
Affected endpoints:
Authorize Endpoint:
•	OLD: {{WU_URL}}WebUntis/api/sso/{{SCHOOL}}/authorize/…
•	NEW: {{WU_URL}}WebUntis/api/sso/v2/{{TENANT_ID}}/authorize/…
Token Endpoint:
•	OLD: {{WU_URL}}WebUntis/api/sso/{{SCHOOL}}/token/…
•	NEW: {{WU_URL}}WebUntis/api/sso/v2/{{TENANT_ID}}/token/…
 
What does this mean for you?
The new endpoints are already available on integration and production.
  You should upgrade to the new endpoints within the next months, because the old endpoints are now deprecated and will be removed before next summer.
 
 If you have not saved the tenantId until now, you might need to migrate your data from schoolname to tenantId. Please get in contact with us, we can provide a mapping-table.
 The documentation in the helpcenter is up2date: https://help.untis.at/hc/de/articles/4886722226834-Authorization-documentation-for-integration-partners
 If you have any questions, feel free to contact us in your teams-channel.

**Comment by rschrenk** [comment]
https://github.com/center-for-learning-management/moodle-local_webuntis/pull/9

**Comment by rschrenk** [comment]
von meiner Seite erledigt. Kann man das schließen?
